### ISSUE TITLE
Number validation

### ISSUE THREAD

**Issue by fanatid** [ethereumjs/ethrpc#33]
Number validation allow number to be `null` or `undefined` https://github.com/ethereumjs/ethrpc/blob/4f3789895d5ad7830befe629f7bb304afb28ecd0/src/validate/validate-number.js#L5-L6
transaction validator uses this validator for gas, gas price, value, nonce -- all this fields can be empty? (`null`/`undefined`)

**Comment by MicahZoltu** [comment]
The number validator is meant to be a fairly lenient so that it can be used in places that allow for null/missing numbers.  Ideally, any place that calls it where null/undefined is not allowed should also check for that.  If we disallowed null/undefined, then there would be a number of call sites that would get a bit uglier.

**Comment by fanatid** [comment]
I understand, but this validator is used in tx validator which is used before send tx to node. Should tx validation be changed then?

**Comment by MicahZoltu** [comment]
If null/undefined are not allowed in that context, then yeah, they should verify that.  Which number on the transaction specifically are you concerned with?  I believe all of the ones you listed are optional (meaning they can be null/missing).  See https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction for reference on optionality.

**Comment by fanatid** [comment]
You are right, only `from` is required, did not known about this.
